# Generated by Django 5.0.6 on 2024-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWB',
            fields=[
                ('awb_number', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('pieces_received', models.PositiveIntegerField()),
                ('weight_received', models.PositiveIntegerField()),
                ('weight_on_hand', models.PositiveIntegerField()),
                ('pieces_on_hand', models.PositiveIntegerField()),
                ('consignee', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('hours_remaining', models.IntegerField()),
                ('priority', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('station', models.CharField(max_length=6)),
                ('remarks', models.CharField(max_length=50)),
                ('sla_report', models.BooleanField(default=False)),
                ('top_20_report', models.BooleanField(default=False)),
                ('priority_report', models.BooleanField(default=False)),
                ('sent_awb_indication', models.BooleanField(default=False)),
                ('new_awb_indication', models.BooleanField(default=False)),
                ('partial_indication', models.BooleanField(default=False)),
            ],
        ),
    ]
