# Generated by Django 5.0.6 on 2024-06-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awb',
            old_name='new_awb_indication',
            new_name='new_awb',
        ),
        migrations.RenameField(
            model_name='awb',
            old_name='partial_indication',
            new_name='partial_sent_awb',
        ),
        migrations.RenameField(
            model_name='awb',
            old_name='sent_awb_indication',
            new_name='sent_awb',
        ),
    ]
