# Generated by Django 5.0.6 on 2024-06-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_new_awb_indication_awb_new_awb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awb',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
